### ISSUE TITLE
Issue with NaN values in sqrt_beta_pred of the IG model

### ISSUE THREAD

**Issue by neryah** [vicliv/DTE#2]
I’m encountering an issue where the model's prediction is returning NaN values.

After executing the line:
sqrt_beta_pred = self.model(x_noisy)

Upon inspection, the output is:
(Pdb) sqrt_beta_pred
tensor([[nan],
        [nan],
        [nan],
        ...
        [nan]], device='cuda:0', grad_fn=<AddmmBackward0>)

And the input x_noisy looks like:
(Pdb) x_noisy
tensor([[-0.1985,  0.8690,  3.1156,  ...,  2.5546, -0.0584,  0.0749],
        [ 0.2889,  0.0399, -1.1737,  ...,  0.3547, -0.0621, -0.9403],
        ...
        [-0.6547,  0.0246, -0.3291,  ..., -0.2791, -0.6015,  0.7493]],
       device='cuda:0', grad_fn=<AddBackward0>)

It appears that x_noisy contains reasonable values, but the model output is NaNs across the board.

What could be causing this behavior?

**Comment by vicliv** [comment]
That is weird, I don't have that issue in my runs. Did you modify anything in the code?

**Comment by neryah** [comment]
You’re right, it might be an issue in my code. I’ll check it out. Please ignore for now unless I ping here.

**Comment by neryah** [comment]
I will remove this issue;
A little question - I saw you changed back:

At class DTEInverseGamma(DTE):
from:
    def __init__(self, seed = 0, model_name = "DTE_inverse_gamma", hidden_size = [128, 128], epochs = 400, batch_size = 64, lr = 1e-4, weight_decay = 0, T=300):        
        super().__init__(seed, model_name, hidden_size, epochs, batch_size, lr, weight_decay, T, 0)
To:
    def __init__(self, seed = 0, model_name = "DTE_inverse_gamma", hidden_size = [256, 512, 256], epochs = 400, batch_size = 64, lr = 1e-4, weight_decay = 5e-4, T=400, device=None):        
        super().__init__(seed, model_name, hidden_size, epochs, batch_size, lr, weight_decay, T, 0, device)
        
Could you advise which version you think is better?

**Comment by vicliv** [comment]
I think the second one is better (the current version).

**Comment by neryah** [comment]
Thank you. Since I can’t delete the issue, I’ve closed it. Feel free to delete it.
