### ISSUE TITLE
Difference between the 121 datasets in the code and the 57 in your tables

### ISSUE THREAD

**Issue by neryah** [vicliv/DTE#3]
In the ‘Settings and Results’ section:
It seems like you calculated the average results based on the tables there with a total of 57 datasets.
However, in the code, I see a total of 121 datasets.

Could you clarify:
	1.	What caused the difference?
	2.	How did you aggregate the 121 datasets into 57 (if aggregation was done)?

Datasets:
57 in table:
['aloi', 'amazon', 'annthyroid', 'backdoor', 'breastw', 'campaign', 'cardio', 'cardiotocography', 'celeba', 'census', 'cover', 'donors', 'fault', 'fraud', 'glass', 'hepatitis', 'http', 'imdb', 'internetads', 'ionosphere', 'landsat', 'letter', 'lymphography', 'magic.gamma', 'mammography', 'mnist', 'musk', 'optdigits', 'pageblocks', 'pendigits', 'pima', 'satellite', 'satimage-2', 'shuttle', 'skin', 'smtp', 'spambase', 'speech', 'stamps', 'thyroid', 'vertebral', 'vowels', 'waveform', 'wbc', 'wdbc', 'wilt', 'wine', 'wpbc', 'yeast', 'yelp', 'MNIST-C', 'FashionMNIST', 'CIFAR10', 'SVHN', 'MVTec-AD', '20news', 'agnews']

121 from the code:
['26_optdigits', '42_WBC', '21_Lymphography', '8_celeba', '33_skin', '34_smtp', '28_pendigits', '39_vertebral', '11_donors', '43_WDBC', '7_Cardiotocography', '36_speech', '5_campaign', '44_Wilt', '10_cover', '46_WPBC', '37_Stamps', '2_annthyroid', '27_PageBlocks', '31_satimage-2', '3_backdoor', '38_thyroid', '29_Pima', '24_mnist', '15_Hepatitis', '22_magic.gamma', '16_http', '32_shuttle', '12_fault', '47_yeast', '13_fraud', '35_SpamBase', '41_Waveform', '17_InternetAds', '6_cardio', '23_mammography', '40_vowels', '9_census', '45_wine', '25_musk', '1_ALOI', '18_Ionosphere', '20_letter', '19_landsat', '14_glass', '30_satellite', '4_breastw', 'MVTec-AD_transistor', 'MVTec-AD_hazelnut', 'SVHN_3', 'MNIST-C_spatter', 'MNIST-C_glass_blur', 'MVTec-AD_pill', 'MNIST-C_rotate', 'MVTec-AD_screw', 'SVHN_8', 'SVHN_9', 'MNIST-C_dotted_line', 'MNIST-C_shear', 'FashionMNIST_3', 'MVTec-AD_toothbrush', 'FashionMNIST_2', 'FashionMNIST_0', 'FashionMNIST_1', 'FashionMNIST_5', 'MNIST-C_identity', 'MVTec-AD_leather', 'FashionMNIST_4', 'FashionMNIST_6', 'CIFAR10_8', 'CIFAR10_9', 'MVTec-AD_metal_nut', 'FashionMNIST_7', 'MNIST-C_motion_blur', 'MNIST-C_stripe', 'MNIST-C_impulse_noise', 'MNIST-C_translate', 'CIFAR10_4', 'CIFAR10_5', 'FashionMNIST_9', 'MNIST-C_brightness', 'CIFAR10_7', 'CIFAR10_6', 'FashionMNIST_8', 'CIFAR10_2', 'MVTec-AD_tile', 'CIFAR10_3', 'MVTec-AD_carpet', 'CIFAR10_1', 'MVTec-AD_capsule', 'CIFAR10_0', 'MNIST-C_canny_edges', 'SVHN_7', 'MVTec-AD_grid', 'MNIST-C_fog', 'MVTec-AD_bottle', 'SVHN_6', 'SVHN_4', 'MVTec-AD_wood', 'MVTec-AD_zipper', 'MVTec-AD_cable', 'SVHN_5', 'MNIST-C_zigzag', 'SVHN_1', 'MNIST-C_scale', 'SVHN_0', 'SVHN_2', 'MNIST-C_shot_noise', 'yelp', 'agnews_3', '20news_5', 'agnews_1', 'agnews_0', '20news_2', '20news_3', '20news_1', '20news_0', 'amazon', '20news_4', 'imdb', 'agnews_2']

**Comment by vicliv** [comment]
The results from all datasets that have multiple classes have been averaged together (MNIST-C, CIFAR10, FaschionMNIST, MNIST-C, SVHN, agnews, 20news, MVTec-AD). 

For example, CIFAR-10, having 10 classes, is made as an anomaly dataset by setting one class as the anomaly, thus creating 10 different datasets. The results are averaged together for these 10 different synthesized datasets.

**Comment by neryah** [comment]
Thank you!
For datasets like CIFAR-10, where 10 anomaly datasets are synthesized, is the final averaged result treated as one dataset (weight = 1/57), or do the individual synthesized datasets contribute to the weight distribution?

**Comment by vicliv** [comment]
Yes it is treated as one dataset.
